name: Build development Docker image

on:
  workflow_dispatch:

jobs:
  build_dev_image:
    runs-on: ubuntu-22.04

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Build Image
      run: |
        docker build --force-rm -t 3fs-builder -f dockerfile/dev.dockerfile .

    - name: Save Image
      run: |
        docker save -o 3fs-builder.tar 3fs-builder:latest

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{github.sha}}
        release_name: 3fs-builder-image
        draft: false
        prerelease: false

    - name: Upload Docker image to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./3fs-builder.tar
        asset_name: 3fs-builder.tar
        asset_content_type: application/x-tar